import '../models/triage_encounter.dart';

/// Build a plain-text referral note from a triage encounter.
///
/// Used for sharing via SMS, WhatsApp, email, or printing.
String buildReferralNote(TriageEncounter encounter) {
  final time =
      '${encounter.timestamp.day}/${encounter.timestamp.month}/${encounter.timestamp.year} '
      '${encounter.timestamp.hour.toString().padLeft(2, '0')}:'
      '${encounter.timestamp.minute.toString().padLeft(2, '0')}';

  final buffer = StringBuffer();
  buffer.writeln('═══════════════════════════════════════');
  buffer.writeln('  MEDLINGUA REFERRAL NOTE');
  buffer.writeln('═══════════════════════════════════════');
  buffer.writeln();
  buffer.writeln('Date: $time');
  buffer.writeln('Triage ID: ${encounter.id.substring(0, 8)}');
  buffer.writeln();
  buffer.writeln('── PATIENT INFORMATION ──');
  buffer.writeln('Name: ${encounter.patientName}');
  if (encounter.patientAge != null) {
    buffer.writeln('Age: ${encounter.patientAge} years');
  }
  if (encounter.patientGender != null) {
    buffer.writeln('Gender: ${encounter.patientGender}');
  }
  buffer.writeln('Language: ${encounter.inputLanguage.toUpperCase()}');
  buffer.writeln();
  buffer.writeln('── ASSESSMENT ──');
  buffer.writeln('Severity: ${encounter.severity.label}');
  buffer.writeln('Confidence: ${(encounter.confidenceScore * 100).toInt()}%');
  buffer.writeln();
  buffer.writeln('Presenting Symptoms:');
  buffer.writeln(encounter.symptoms);
  buffer.writeln();
  buffer.writeln('Suspected Condition:');
  buffer.writeln(encounter.diagnosis);
  buffer.writeln();
  buffer.writeln('── RECOMMENDED ACTIONS ──');
  buffer.writeln(encounter.recommendation);
  buffer.writeln();
  buffer.writeln('═══════════════════════════════════════');
  buffer.writeln('Generated by MedLingua (AI-assisted)');
  buffer.writeln('This does NOT replace clinical diagnosis.');
  buffer.writeln('═══════════════════════════════════════');
  return buffer.toString();
}
